# Generated by Django 6.1.1 on 2026-09-14 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='The topic/category the adaptive engine uses for personalization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='learning.category'),
        ),
    ]
