# Generated by Django 6.1.1 on 2026-09-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text="True for questions generated on-the-fly by Gemini; False for the teacher's own question bank."),
        ),
    ]
