# Generated by Django 5.2.17 on 2026-09-22 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_question_is_ai_generated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'verbose_name': 'Course Progress', 'verbose_name_plural': 'Course Progresses'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order_number'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'verbose_name': 'Quiz Attempt', 'verbose_name_plural': 'Quiz Attempts'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': 'Quiz Question', 'verbose_name_plural': 'Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='studentperformance',
            options={'verbose_name': 'Student Performance', 'verbose_name_plural': 'Student Performances'},
        ),
        migrations.AlterModelOptions(
            name='studyplan',
            options={'verbose_name': 'Study Plan', 'verbose_name_plural': 'Study Plans'},
        ),
        migrations.AlterModelOptions(
            name='studysession',
            options={'verbose_name': 'Study Session', 'verbose_name_plural': 'Study Sessions'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'User Answer', 'verbose_name_plural': 'User Answers'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=255, verbose_name='Choice Text'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='learning.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_lessons',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Lessons'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='completion_percentage',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Completion Percentage'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Accessed'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10, verbose_name='Difficulty Level'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Is AI Generated'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='learning.category', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='learning.lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Passing Score'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Started At'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='order_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_links', to='learning.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='learning.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0, verbose_name='Correct Answers'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performances', to='learning.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performances', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='learning.category', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='wrong_answers',
            field=models.PositiveIntegerField(default=0, verbose_name='Wrong Answers'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='action_items',
            field=models.TextField(verbose_name='Action Items'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plans', to='learning.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='learning.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Duration (Minutes)'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Answer Text'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Answered At'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.quizattempt', verbose_name='Attempt'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='learning.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.choice', verbose_name='Selected Choice'),
        ),
        migrations.CreateModel(
            name='LiveLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('scheduled_at', models.DateTimeField(verbose_name='Scheduled At')),
                ('zoom_url', models.URLField(blank=True, default='https://zoom.us/j/smart-elearning', verbose_name='Zoom URL')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_lectures', to='learning.course', verbose_name='Course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_lectures', to=settings.AUTH_USER_MODEL, verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Live Lecture',
                'verbose_name_plural': 'Live Lectures',
            },
        ),
    ]
