# Generated by Django 6.1.1 on 2026-09-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'verbose_name': 'Points entry', 'verbose_name_plural': 'Points log'},
        ),
    ]
