# Generated by Django 6.1.1 on 2026-09-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_aimessage_session_studenttask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindfulnesscontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mindfulness/'),
        ),
        migrations.AlterField(
            model_name='mindfulnesscontent',
            name='text',
            field=models.TextField(blank=True, help_text='Optional if an image already contains the text'),
        ),
    ]
