from django.contrib import admin
from .models import (
    Category, Course, Lesson, Enrollment, CourseProgress, Quiz, Question,
    QuizQuestion, Choice, QuizAttempt, UserAnswer, StudentPerformance,
    StudySession, StudyPlan,
)


class InstructorOnlyAdminMixin:
    """
    Restricts add/change/delete to staff whose role is INSTRUCTOR (or a
    superuser). This is what actually stops a STUDENT account from editing
    course content — even if that account somehow ended up with is_staff=True,
    it still can't touch Category/Course/Lesson/Quiz/Question/Choice here.
    Superusers always pass, since they're the platform administrators.
    """

    def _is_instructor(self, request):
        user = request.user
        return user.is_superuser or getattr(user, 'role', None) == 'INSTRUCTOR'

    def has_add_permission(self, request):
        return self._is_instructor(request) and super().has_add_permission(request)

    def has_change_permission(self, request, obj=None):
        return self._is_instructor(request) and super().has_change_permission(request, obj)

    def has_delete_permission(self, request, obj=None):
        return self._is_instructor(request) and super().has_delete_permission(request, obj)


class CategoryAdmin(InstructorOnlyAdminMixin, admin.ModelAdmin):
    pass


class CourseAdmin(InstructorOnlyAdminMixin, admin.ModelAdmin):
    pass


class LessonAdmin(InstructorOnlyAdminMixin, admin.ModelAdmin):
    pass


class QuizAdmin(InstructorOnlyAdminMixin, admin.ModelAdmin):
    pass


class QuestionAdmin(InstructorOnlyAdminMixin, admin.ModelAdmin):
    pass


class ChoiceAdmin(InstructorOnlyAdminMixin, admin.ModelAdmin):
    pass


class QuizQuestionAdmin(InstructorOnlyAdminMixin, admin.ModelAdmin):
    pass


admin.site.register(Category, CategoryAdmin)
admin.site.register(Course, CourseAdmin)
admin.site.register(Lesson, LessonAdmin)
admin.site.register(Quiz, QuizAdmin)
admin.site.register(Question, QuestionAdmin)
admin.site.register(Choice, ChoiceAdmin)
admin.site.register(QuizQuestion, QuizQuestionAdmin)

# These are records generated by student activity, not course content —
# left as regular staff-editable models (still requires is_staff to reach
# the admin at all; a plain STUDENT account never gets that by default).
admin.site.register(Enrollment)
admin.site.register(CourseProgress)
admin.site.register(QuizAttempt)
admin.site.register(UserAnswer)
admin.site.register(StudentPerformance)
admin.site.register(StudySession)
admin.site.register(StudyPlan)
