"""
Adaptive quiz engine — hybrid of two sources, both clearly labeled to the
student in the UI:

1. TEACHER BANK (7 questions): real Question rows the teacher entered in
   the Django admin, picked by the student's assessed level.
2. GENAI CREATED (3 questions): freshly generated by Gemini at the same
   difficulty level, using prompt engineering, to round the quiz up to 10.
   These are still saved as real Question/Choice rows (tagged
   is_ai_generated=True) so grading works exactly the same way as for the
   teacher's own questions — nothing about answer-checking is special-cased.

Level assessment thresholds (exact spec):
- No previous attempts yet in this course -> EASY (fresh start).
- Average score < 50%  -> EASY
- Average score 50-79%  -> MEDIUM
- Average score >= 80%  -> HARD
"""
import json
import logging
import random

from django.conf import settings
from django.db.models import Avg

from .models import Question, QuizQuestion, StudentPerformance, QuizAttempt, Choice

logger = logging.getLogger(__name__)

LEVEL_ORDER = ['EASY', 'MEDIUM', 'HARD']
REAL_QUESTIONS_TARGET = 7
AI_QUESTIONS_TARGET = 3


def assess_student_level(student, course) -> str:
    """Returns 'EASY', 'MEDIUM', or 'HARD' per the exact thresholds above."""
    attempts = QuizAttempt.objects.filter(
        student=student, quiz__lesson__course=course, score__isnull=False
    )
    if not attempts.exists():
        return 'EASY'

    avg_score = attempts.aggregate(avg=Avg('score'))['avg'] or 0
    if avg_score >= 80:
        return 'HARD'
    if avg_score >= 50:
        return 'MEDIUM'
    return 'EASY'


def _select_real_questions(quiz, student, course, level, limit=REAL_QUESTIONS_TARGET):
    """Picks `limit` questions from the TEACHER'S OWN bank only (never AI-generated)."""
    quiz_question_ids = list(
        QuizQuestion.objects.filter(quiz=quiz).values_list('question_id', flat=True)
    )
    all_questions = list(
        Question.objects.filter(id__in=quiz_question_ids, is_ai_generated=False)
        .select_related('topic')
        .prefetch_related('choices')
    )

    by_level = {lvl: [q for q in all_questions if q.difficulty_level == lvl] for lvl in LEVEL_ORDER}

    primary_pool = by_level.get(level, [])[:]
    random.shuffle(primary_pool)
    selected = primary_pool[:limit]

    if len(selected) < limit:
        fill_order = ['EASY', 'HARD'] if level == 'MEDIUM' else [lvl for lvl in LEVEL_ORDER if lvl != level]
        for lvl in fill_order:
            if len(selected) >= limit:
                break
            extra = by_level.get(lvl, [])[:]
            random.shuffle(extra)
            needed = limit - len(selected)
            selected.extend(extra[:needed])

    # Within the chosen set, still surface weak-topic questions first.
    performances = StudentPerformance.objects.filter(student=student, course=course).select_related('topic')
    weakness_by_topic = {p.topic_id: p.weakness_score for p in performances}
    selected.sort(key=lambda q: -weakness_by_topic.get(q.topic_id, 0.15))

    return selected[:limit]


def _build_genai_prompt(topic_name, level, count, existing_texts):
    avoid_list = "\n".join(f"- {t}" for t in existing_texts[:10]) or "(none)"
    return f"""
You are a quiz question generator for an educational platform teaching "{topic_name}".

Generate exactly {count} multiple-choice questions at difficulty level "{level}"
(EASY = basic recall/definitions, MEDIUM = applying a concept, HARD = multi-step
or edge-case reasoning).

Rules:
- Each question must have exactly 4 choices, with exactly ONE marked correct.
- Do not repeat or closely paraphrase any of these existing questions:
{avoid_list}
- Keep each question and choice short and unambiguous.
- Respond with ONLY raw JSON, no markdown fences, no commentary, in exactly
  this shape:

{{
  "questions": [
    {{
      "question_text": "...",
      "choices": [
        {{"text": "...", "is_correct": true}},
        {{"text": "...", "is_correct": false}},
        {{"text": "...", "is_correct": false}},
        {{"text": "...", "is_correct": false}}
      ]
    }}
  ]
}}
"""


def generate_ai_questions(quiz, topic, level, count=AI_QUESTIONS_TARGET):
    """
    Asks Gemini for `count` fresh multiple-choice questions at the given
    level/topic, saves them as real Question/Choice rows tagged
    is_ai_generated=True, links them to this quiz, and returns them.

    Never raises: if the API key is missing or the call fails for any
    reason, logs the error and returns an empty list so the caller can top
    up with extra real questions instead of breaking the quiz page.
    """
    api_key = getattr(settings, 'GEMINI_API_KEY', None)
    if not api_key or not topic:
        return []

    try:
        from google import genai
        from google.genai import types

        client = genai.Client(api_key=api_key)
        existing_texts = list(
            Question.objects.filter(topic=topic, is_ai_generated=False).values_list('question_text', flat=True)
        )
        prompt = _build_genai_prompt(topic.name, level, count, existing_texts)

        response = client.models.generate_content(
            model="gemini-3.6-flash",
            contents=prompt,
            config=types.GenerateContentConfig(response_mime_type="application/json"),
        )

        raw_text = (response.text or '').strip()
        # Defensive: strip markdown fences if the model adds them despite
        # the JSON-mode config (some models still do this occasionally).
        if raw_text.startswith('```'):
            raw_text = raw_text.strip('`')
            if raw_text.lower().startswith('json'):
                raw_text = raw_text[4:].strip()

        data = json.loads(raw_text)
        # Defensive: accept either {"questions": [...]} (what we asked for)
        # or a bare [...] list (what some models return despite instructions).
        if isinstance(data, dict):
            items = data.get('questions', [])
        elif isinstance(data, list):
            items = data
        else:
            items = []

        created = []
        for item in items[:count]:
            text = item.get('question_text', '').strip()
            choices = item.get('choices', [])
            if not text or len(choices) < 2:
                continue

            question = Question.objects.create(
                topic=topic,
                question_text=text,
                difficulty_level=level,
                is_ai_generated=True,
            )
            for choice in choices:
                Choice.objects.create(
                    question=question,
                    choice_text=str(choice.get('text', '')).strip(),
                    is_correct=bool(choice.get('is_correct')),
                )
            QuizQuestion.objects.get_or_create(quiz=quiz, question=question)
            created.append(question)

        return created

    except Exception as e:
        logger.warning("AI question generation failed: %s", e)
        print(f"[AI QUESTION GENERATION FAILED] {e}")  # guaranteed visible in the runserver console
        return []


def build_adaptive_quiz(student, quiz, course, limit: int = 10):
    """
    Returns a combined list of up to `limit` Question objects:
    ~7 from the teacher's real bank (matched to the student's level) and
    ~3 freshly generated by Gemini at the same level. If Gemini generation
    fails or returns fewer than requested, tops up from the real bank so
    the student still gets a full quiz.
    """
    level = assess_student_level(student, course)

    real_target = min(REAL_QUESTIONS_TARGET, limit)
    real_questions = _select_real_questions(quiz, student, course, level, limit=real_target)

    ai_target = limit - len(real_questions)
    ai_questions = []
    if ai_target > 0:
        # Bug fix: previously, if the teacher's questions had no topic/category
        # assigned in admin (an easy thing to forget — it's optional), `topic`
        # ended up None and AI generation was silently skipped every time,
        # even with a perfectly valid API key. Now we always fall back to the
        # course's own category when the question itself has none.
        topic = None
        if real_questions:
            topic = real_questions[0].topic
        if not topic:
            topic = getattr(course, 'category', None)
        ai_questions = generate_ai_questions(quiz, topic, level, count=ai_target)

    combined = real_questions + ai_questions

    # If AI generation came back short (e.g. no internet), fill the rest
    # from the real bank so the quiz still has `limit` questions.
    if len(combined) < limit:
        used_ids = {q.id for q in combined}
        extra = _select_real_questions(quiz, student, course, level, limit=limit)
        for q in extra:
            if q.id not in used_ids and len(combined) < limit:
                combined.append(q)
                used_ids.add(q.id)

    # Within the chosen difficulty set, still surface weak-topic questions
    # first (this is what makes it "adaptive" beyond just difficulty).
    performances = StudentPerformance.objects.filter(student=student, course=course).select_related('topic')
    weakness_by_topic = {p.topic_id: p.weakness_score for p in performances}
    combined.sort(key=lambda q: -weakness_by_topic.get(q.topic_id, 0.15))

    return combined[:limit]


def record_quiz_result(attempt, answers_data):
    """
    answers_data: list of dicts [{"question_id": .., "selected_choice_id": .., "is_correct": bool}, ...]
    - Creates a UserAnswer row for each question.
    - Creates/updates StudentPerformance for each question's topic.
    - Returns the final score as a percentage.
    """
    from .models import UserAnswer

    course = attempt.quiz.lesson.course
    correct_count = 0

    for item in answers_data:
        question = Question.objects.select_related('topic').get(id=item['question_id'])
        is_correct = bool(item.get('is_correct'))
        if is_correct:
            correct_count += 1

        UserAnswer.objects.create(
            attempt=attempt,
            question=question,
            selected_choice_id=item.get('selected_choice_id'),
            is_correct=is_correct,
        )

        if question.topic_id:
            perf, _ = StudentPerformance.objects.get_or_create(
                student=attempt.student, course=course, topic=question.topic,
                defaults={'correct_answers': 0, 'wrong_answers': 0},
            )
            if is_correct:
                perf.correct_answers += 1
            else:
                perf.wrong_answers += 1
            perf.save(update_fields=['correct_answers', 'wrong_answers'])

    total = len(answers_data) or 1
    score = round((correct_count / total) * 100, 2)
    return score
